<?php
/**
 * Admin UI — menu page with settings + one-click audit.
 */

if (!defined('ABSPATH')) {
    exit;
}

class GEO_AI_OS_Admin
{
    public static function register()
    {
        add_action('admin_menu', [__CLASS__, 'menu']);
        add_action('admin_init', [__CLASS__, 'settings']);
        add_action('admin_post_geo_ai_os_run_audit', [__CLASS__, 'handle_run_audit']);
        add_action('admin_post_geo_ai_os_generate_faq', [__CLASS__, 'handle_generate_faq']);
    }

    public static function menu()
    {
        add_menu_page(
            'GEO AI OS',
            'GEO AI OS',
            'manage_options',
            'geo-ai-os',
            [__CLASS__, 'render'],
            'dashicons-chart-area',
            58
        );
    }

    public static function settings()
    {
        register_setting('geo_ai_os', 'geo_ai_os_api_url');
        register_setting('geo_ai_os', 'geo_ai_os_api_key');
    }

    public static function render()
    {
        if (!current_user_can('manage_options')) {
            return;
        }
        $api_url = esc_attr(get_option('geo_ai_os_api_url', 'http://localhost:3000'));
        $last_audit = get_transient('geo_ai_os_last_audit');
        $last_message = get_transient('geo_ai_os_last_message');
        $site_url = esc_attr(home_url('/'));
        $nonce_audit = wp_create_nonce('geo_ai_os_run_audit');
        $nonce_faq = wp_create_nonce('geo_ai_os_generate_faq');

        ?>
        <div class="wrap">
            <h1>GEO AI Operating System</h1>
            <p class="description">Audit this site for AI search visibility and inject GEO-optimized markup.</p>

            <h2>Connection</h2>
            <form method="post" action="options.php">
                <?php settings_fields('geo_ai_os'); ?>
                <table class="form-table">
                    <tr>
                        <th><label for="geo_ai_os_api_url">API URL</label></th>
                        <td><input type="text" id="geo_ai_os_api_url" name="geo_ai_os_api_url" value="<?php echo $api_url; ?>" class="regular-text" /></td>
                    </tr>
                </table>
                <?php submit_button('Save settings'); ?>
            </form>

            <h2>Run audit</h2>
            <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>">
                <input type="hidden" name="action" value="geo_ai_os_run_audit" />
                <input type="hidden" name="_wpnonce" value="<?php echo $nonce_audit; ?>" />
                <input type="text" name="url" value="<?php echo $site_url; ?>" class="regular-text" />
                <?php submit_button('Run GEO Audit', 'primary', 'submit', false); ?>
            </form>

            <?php if ($last_message): ?>
                <div class="notice notice-info"><p><?php echo esc_html($last_message); ?></p></div>
            <?php endif; ?>

            <?php if ($last_audit): ?>
                <h2>Most recent audit</h2>
                <p>
                    <strong>Overall:</strong> <?php echo intval($last_audit['overallScore']); ?>/100<br />
                    <strong>URL:</strong> <code><?php echo esc_html($last_audit['url']); ?></code><br />
                    <strong>Audit ID:</strong> <code><?php echo esc_html($last_audit['id']); ?></code>
                </p>
                <?php if (!empty($last_audit['narrative'])): ?>
                    <p><?php echo esc_html($last_audit['narrative']); ?></p>
                <?php endif; ?>

                <h3>Quick fixes</h3>
                <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>">
                    <input type="hidden" name="action" value="geo_ai_os_generate_faq" />
                    <input type="hidden" name="_wpnonce" value="<?php echo $nonce_faq; ?>" />
                    <input type="hidden" name="audit_id" value="<?php echo esc_attr($last_audit['id']); ?>" />
                    <?php submit_button('Generate FAQ schema + auto-inject', 'secondary', 'submit', false); ?>
                </form>
            <?php endif; ?>

            <h2>Notes</h2>
            <p>
                Live patching for WordPress is implemented as a <code>wp_head</code> injector
                (see <code>includes/class-geo-schema-injector.php</code>). It currently injects FAQ JSON-LD generated by the GEO backend.
                Other artifact types (llms.txt, AI summary, answer-first rewrites) are produced by the backend but not yet wired into theme hooks — see TODO comments in <code>class-geo-schema-injector.php</code>.
            </p>
        </div>
        <?php
    }

    public static function handle_run_audit()
    {
        if (!current_user_can('manage_options')) {
            wp_die('Forbidden', 403);
        }
        check_admin_referer('geo_ai_os_run_audit');
        $url = isset($_POST['url']) ? esc_url_raw(wp_unslash($_POST['url'])) : home_url('/');
        $result = GEO_AI_OS_API::run_audit($url);

        if (is_wp_error($result)) {
            set_transient('geo_ai_os_last_message', 'Audit failed: ' . $result->get_error_message(), 60);
        } else {
            set_transient('geo_ai_os_last_audit', $result, DAY_IN_SECONDS);
            set_transient('geo_ai_os_last_message', 'Audit complete.', 60);
        }
        wp_safe_redirect(admin_url('admin.php?page=geo-ai-os'));
        exit;
    }

    public static function handle_generate_faq()
    {
        if (!current_user_can('manage_options')) {
            wp_die('Forbidden', 403);
        }
        check_admin_referer('geo_ai_os_generate_faq');
        $audit_id = isset($_POST['audit_id']) ? sanitize_text_field(wp_unslash($_POST['audit_id'])) : '';
        if (!$audit_id) {
            wp_safe_redirect(admin_url('admin.php?page=geo-ai-os'));
            exit;
        }
        $artifact = GEO_AI_OS_API::generate_artifact($audit_id, 'faq-schema');
        if (is_wp_error($artifact) || !$artifact) {
            set_transient('geo_ai_os_last_message', 'FAQ generation failed.', 60);
        } else {
            update_option('geo_ai_os_injected_faq_schema', $artifact['content']);
            set_transient('geo_ai_os_last_message', 'FAQ schema generated and queued for injection on <head>.', 60);
        }
        wp_safe_redirect(admin_url('admin.php?page=geo-ai-os'));
        exit;
    }
}
