/**
 * Mock AI provider — deterministic, zero-key responses.
 *
 * Critical property: GIVEN THE SAME PROMPT IT RETURNS THE SAME OUTPUT.
 * This makes the entire product testable and reproducible without spending
 * money on API calls. Output is rule-based + hash-seeded, NOT random.
 *
 * Structured outputs are produced by walking the Zod schema and synthesizing
 * plausible values keyed off the prompt content.
 */

import { createHash } from 'crypto';
import { z } from 'zod';
import {
  AIProviderError,
  type AIProvider,
  type GenerateEmbeddingInput,
  type GenerateEmbeddingResult,
  type GenerateStructuredInput,
  type GenerateStructuredResult,
  type GenerateTextInput,
  type GenerateTextResult,
} from '../types';

function seedFrom(text: string): number {
  const hash = createHash('sha256').update(text).digest();
  return hash.readUInt32BE(0);
}

class SeededRng {
  constructor(private state: number) {
    if (this.state === 0) this.state = 1;
  }
  next(): number {
    this.state = (this.state * 1664525 + 1013904223) >>> 0;
    return this.state / 0xffffffff;
  }
  pick<T>(arr: readonly T[]): T {
    return arr[Math.floor(this.next() * arr.length)] as T;
  }
  int(min: number, max: number): number {
    return Math.floor(this.next() * (max - min + 1)) + min;
  }
}

function tokenCount(s: string): number {
  return Math.max(1, Math.ceil(s.length / 4));
}

const SAMPLE_BRANDS = [
  'Apple', 'Google', 'Microsoft', 'Amazon', 'OpenAI', 'Anthropic',
  'Daikin', 'Mitsubishi Electric', 'Fujitsu', 'Panasonic', 'LG',
  'Ahrefs', 'Semrush', 'Moz', 'Yoast', 'SurferSEO',
];

const SAMPLE_DOMAINS = [
  'wikipedia.org', 'nytimes.com', 'theverge.com', 'techcrunch.com',
  'github.com', 'stackoverflow.com', 'medium.com', 'forbes.com',
];

function generateMockText(prompt: string, system?: string): string {
  const rng = new SeededRng(seedFrom(prompt + (system ?? '')));
  const sentences = [
    'Based on the available information, the most relevant answer is structured below.',
    'The key insight relates to how AI systems extract and cite content.',
    'Several authoritative sources discuss this topic in depth.',
    'A recommended approach focuses on semantic clarity and answer-first structure.',
    'Schema.org markup and FAQ blocks significantly improve LLM citation probability.',
  ];
  const pickedCount = rng.int(2, 4);
  const picks: string[] = [];
  for (let i = 0; i < pickedCount; i++) picks.push(rng.pick(sentences));
  return picks.join(' ');
}

const SHORT_FIELD_HINTS: Record<string, (rng: SeededRng) => string> = {
  brand: (rng) => rng.pick(SAMPLE_BRANDS),
  name: (rng) => rng.pick(SAMPLE_BRANDS),
  domain: (rng) => rng.pick(SAMPLE_DOMAINS),
  url: (rng) => `https://${rng.pick(SAMPLE_DOMAINS)}/article-${rng.int(100, 999)}`,
  kind: (rng) => rng.pick(['organization', 'product', 'person', 'place', 'concept']),
  type: (rng) => rng.pick(['Article', 'FAQPage', 'Product', 'Organization', 'BreadcrumbList']),
  question: (rng) =>
    rng.pick([
      'What is the best option in 2026?',
      'How does this work?',
      'Why should I choose this?',
      'When was it released?',
    ]),
  answer: () =>
    'The direct answer is summarized in the lead. Supporting details follow with citations to authoritative sources.',
  snippet: (rng) => `…cited by ${rng.pick(SAMPLE_BRANDS)} as a primary source…`,
  rationale: () => 'Generated by the mock provider for offline/testing use; the structure is realistic but the text is synthetic.',
};

function fieldKey(prompt: string): string | null {
  const idx = prompt.lastIndexOf(':');
  if (idx === -1) return null;
  return prompt.slice(idx + 1).toLowerCase();
}

/** Avoid `instanceof` — Next.js can bundle multiple Zod copies, which breaks synthesis. */
function zodTypeName(schema: z.ZodTypeAny): string {
  return (schema._def as { typeName: string }).typeName;
}

function synthesizeFromSchema<T>(schema: z.ZodTypeAny, prompt: string, depth = 0): T {
  const rng = new SeededRng(seedFrom(prompt) + depth);
  const typeName = zodTypeName(schema);

  switch (typeName) {
    case 'ZodObject': {
      const shape = (schema as z.ZodObject<z.ZodRawShape>).shape;
      const out: Record<string, unknown> = {};
      for (const [key, fieldSchema] of Object.entries(shape)) {
        out[key] = synthesizeFromSchema(fieldSchema, prompt + ':' + key, depth + 1);
      }
      return out as T;
    }
    case 'ZodArray': {
      const len = rng.int(2, 4);
      const element = (schema as z.ZodArray<z.ZodTypeAny>).element;
      const arr: unknown[] = [];
      for (let i = 0; i < len; i++) {
        arr.push(synthesizeFromSchema(element, prompt + ':' + i, depth + 1));
      }
      return arr as T;
    }
    case 'ZodOptional':
    case 'ZodNullable':
    case 'ZodDefault':
      return synthesizeFromSchema(schema._def.innerType as z.ZodTypeAny, prompt, depth + 1) as T;
    case 'ZodEffects':
      return synthesizeFromSchema(schema._def.schema as z.ZodTypeAny, prompt, depth + 1) as T;
    case 'ZodEnum': {
      const opts = schema._def.values as readonly string[];
      return rng.pick(opts) as T;
    }
    case 'ZodLiteral':
      return schema._def.value as T;
    case 'ZodUnion': {
      const opts = schema._def.options as z.ZodTypeAny[];
      return synthesizeFromSchema(opts[0], prompt, depth + 1) as T;
    }
    case 'ZodNumber': {
      const key = fieldKey(prompt);
      if (key === 'relevance') {
        return Number((rng.next() * 0.6 + 0.4).toFixed(2)) as unknown as T;
      }
      if (key === 'position' || key === 'count') {
        return rng.int(1, 5) as unknown as T;
      }
      return rng.int(60, 90) as unknown as T;
    }
    case 'ZodBoolean':
      return (rng.next() > 0.5) as unknown as T;
    case 'ZodString': {
      const key = fieldKey(prompt);
      if (key && SHORT_FIELD_HINTS[key]) {
        return SHORT_FIELD_HINTS[key](rng) as unknown as T;
      }
      if (
        key === 'summary' ||
        key === 'narrative' ||
        key === 'description' ||
        key === 'detail' ||
        key === 'reason' ||
        key === 'rationale' ||
        key === 'rewritten'
      ) {
        return generateMockText(prompt + ':str' + depth) as unknown as T;
      }
      return generateMockText(prompt + ':str' + depth) as unknown as T;
    }
    case 'ZodRecord':
      return {} as T;
    default:
      return (`Mock value for ${prompt.slice(0, 40)}`) as unknown as T;
  }
}

export class MockAIProvider implements AIProvider {
  readonly name = 'mock';

  async generateText(input: GenerateTextInput): Promise<GenerateTextResult> {
    const text = generateMockText(input.prompt, input.system);
    const inputTokens = tokenCount(input.prompt + (input.system ?? ''));
    const outputTokens = tokenCount(text);
    return {
      text,
      tokens: { input: inputTokens, output: outputTokens, total: inputTokens + outputTokens },
      model: 'mock-deterministic-v1',
      provider: this.name,
    };
  }

  async generateStructuredOutput<TSchema extends z.ZodTypeAny>(
    input: GenerateStructuredInput<TSchema>,
  ): Promise<GenerateStructuredResult<z.infer<TSchema>>> {
    if (input.schemaName === 'GeoAgentPlan') {
      const { buildMockAgentPlan } = await import('@modules/geo-agent/mock-plan');
      const goalMatch = input.prompt.match(/User goal: "([^"]+)"/);
      const goal = goalMatch?.[1] ?? input.prompt;
      const data = buildMockAgentPlan(goal) as z.infer<TSchema>;
      const parsed = input.schema.safeParse(data);
      if (!parsed.success) {
        throw new AIProviderError(
          `mock GeoAgentPlan did not match schema: ${parsed.error.message}`,
          this.name,
        );
      }
      const inputTokens = tokenCount(input.prompt);
      const outputTokens = tokenCount(JSON.stringify(parsed.data));
      return {
        data: parsed.data,
        tokens: { input: inputTokens, output: outputTokens, total: inputTokens + outputTokens },
        model: 'mock-agent-plan-v1',
        provider: this.name,
      };
    }

    if (input.schemaName === 'GeoContentPack') {
      const { buildMockGeoContentPack } = await import('@modules/geo-content/mock-pack');
      const data = buildMockGeoContentPack(input.prompt) as z.infer<TSchema>;
      const parsed = input.schema.safeParse(data);
      if (!parsed.success) {
        throw new AIProviderError(
          `mock GeoContentPack did not match schema: ${parsed.error.message}`,
          this.name,
        );
      }
      const inputTokens = tokenCount(input.prompt);
      const outputTokens = tokenCount(JSON.stringify(parsed.data));
      return {
        data: parsed.data,
        tokens: { input: inputTokens, output: outputTokens, total: inputTokens + outputTokens },
        model: 'mock-geo-content-v1',
        provider: this.name,
      };
    }

    const synthesized = synthesizeFromSchema<z.infer<TSchema>>(input.schema, input.prompt);
    // Validate so the output really matches the contract; if invalid (rare),
    // surface a friendly error.
    const parsed = input.schema.safeParse(synthesized);
    if (!parsed.success) {
      throw new AIProviderError(
        `mock structured output did not match schema: ${parsed.error.message}`,
        this.name,
      );
    }
    const data = parsed.data;

    const inputTokens = tokenCount(input.prompt);
    const outputTokens = tokenCount(JSON.stringify(data));
    return {
      data,
      tokens: { input: inputTokens, output: outputTokens, total: inputTokens + outputTokens },
      model: 'mock-deterministic-v1',
      provider: this.name,
    };
  }

  async generateEmbedding(input: GenerateEmbeddingInput): Promise<GenerateEmbeddingResult> {
    // 256-dim deterministic vector seeded from text hash
    const seed = seedFrom(input.text);
    const rng = new SeededRng(seed);
    const vector: number[] = [];
    for (let i = 0; i < 256; i++) {
      vector.push(rng.next() * 2 - 1);
    }
    return {
      vector,
      tokens: { input: tokenCount(input.text), output: 0, total: tokenCount(input.text) },
      model: 'mock-embedding-v1',
      provider: this.name,
    };
  }
}

export const mockSampleBrands = SAMPLE_BRANDS;
export const mockSampleDomains = SAMPLE_DOMAINS;
