import {
  ingestAudit,
  ingestAuditSync,
  ingestAuditEmbeddings,
  reindexPatterns,
  backfillIntelligenceFromAudits,
  getMinCohortSamples,
  getEffectiveMinCohortSamples,
  ingestCitationSnapshot,
} from './ingest';
import {
  getBenchmarksForSite,
  getPlaybook,
  getSiteTrend,
  getIntelligenceContext,
  findSimilarCohortChunks,
  recordFixApplied,
  verifyPendingFixOutcomes,
  getCohortInsights,
  getIntelligenceGraphSummary,
} from './queries';

export const intelligenceService = {
  ingestAudit,
  ingestAuditSync,
  ingestAuditEmbeddings,
  reindexPatterns,
  backfillIntelligenceFromAudits,
  getMinCohortSamples,
  getEffectiveMinCohortSamples,
  ingestCitationSnapshot,
  getBenchmarksForSite,
  getPlaybook,
  getSiteTrend,
  getIntelligenceContext,
  findSimilarCohortChunks,
  recordFixApplied,
  verifyPendingFixOutcomes,
  getCohortInsights,
  getIntelligenceGraphSummary,
};

export {
  ingestAudit,
  ingestAuditSync,
  ingestAuditEmbeddings,
  reindexPatterns,
  backfillIntelligenceFromAudits,
  getMinCohortSamples,
  getEffectiveMinCohortSamples,
  ingestCitationSnapshot,
  getBenchmarksForSite,
  getPlaybook,
  getSiteTrend,
  getIntelligenceContext,
  findSimilarCohortChunks,
  recordFixApplied,
  verifyPendingFixOutcomes,
  getCohortInsights,
  getIntelligenceGraphSummary,
};
